# Generated by Django 5.2.7 on 2025-10-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('😂', 'Laugh'), ('😢', 'Sad'), ('😡', 'Angry')], max_length=5)),
                ('count', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main_app.note')),
            ],
        ),
    ]
