# Generated by Django 5.2.7 on 2025-10-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_emojireact'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='emojis',
            field=models.ManyToManyField(blank=True, related_name='notes_emojis', to='main_app.emojireact'),
        ),
    ]
