# Generated by Django 5.2.7 on 2025-10-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_note_emojis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emojireact',
            name='count',
        ),
        migrations.RemoveField(
            model_name='emojireact',
            name='note',
        ),
        migrations.AlterField(
            model_name='emojireact',
            name='emoji',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='note',
            name='emojis',
            field=models.ManyToManyField(blank=True, related_name='notes', to='main_app.emojireact'),
        ),
    ]
