# Generated by Django 5.2.7 on 2025-10-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_emojireact_count_remove_emojireact_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.note')),
            ],
        ),
    ]
