# Generated by Django 5.2.7 on 2025-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='url',
        ),
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
